### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by zmj876902008** [hou-yz/DA_visualization#2]
Hello, thanks for your work. I want to know if I can use my own dataset training model?What would my dataset look like if I could?Thanks for your kind attention and look forward your prompt reply.

**Comment by hou-yz** [comment]
yes, you can try and use your own datasets. to this end, please create your own dataset class, or follow the [ImageFolder](https://pytorch.org/vision/stable/datasets.html#torchvision.datasets.ImageFolder) class in torchvision.

hope this helps,
Yunzhong
