### ISSUE TITLE
da_setting adda seems no effect

### ISSUE THREAD

**Issue by xiaoyuan1996** [hou-yz/DA_visualization#5]
python train_DA.py -d digits --source svhn --target mnist --da_setting adda

Training target model...
Train Epoch: 22, Batch:937, S: [c: 0.000, d: 1.354], Time: 12.886
Testing target model on [source]...
Test, loss: 4.267, prec: 6.4%, Time: 2.465
Testing target model on [target]...
Test, loss: 4.293, prec: 9.8%, Time: 1.192
 73%|████████████████████████████████████████████████████████████████████████████████████▎                              | 22/30 [06:11<02:15, 16.93s/it]Training target model...
Train Epoch: 23, Batch:937, S: [c: 0.000, d: 1.429], Time: 12.536
Testing target model on [source]...
Test, loss: 6.942, prec: 7.8%, Time: 2.410
Testing target model on [target]...
Test, loss: 7.577, prec: 10.3%, Time: 1.235
 77%|████████████████████████████████████████████████████████████████████████████████████████▏                          | 23/30 [06:27<01:57, 16.75s/it]Training target model...
Train Epoch: 24, Batch:937, S: [c: 0.000, d: 1.375], Time: 13.038
Testing target model on [source]...
Test, loss: 14.831, prec: 9.7%, Time: 2.508
Testing target model on [target]...
Test, loss: 15.324, prec: 9.8%, Time: 1.543
 80%|████████████████████████████████████████████████████████████████████████████████████████████                       | 24/30 [06:44<01:41, 16.91s/it]Training target model...
Train Epoch: 25, Batch:937, S: [c: 0.000, d: 1.367], Time: 12.633
Testing target model on [source]...
Test, loss: 6.635, prec: 6.1%, Time: 2.474
Testing target model on [target]...
Test, loss: 7.577, prec: 10.1%, Time: 1.280
 83%|███████████████████████████████████████████████████████████████████████████████████████████████▊                   | 25/30 [07:01<01:23, 16.80s/it]Training target model...
Train Epoch: 26, Batch:937, S: [c: 0.000, d: 1.390], Time: 12.824
Testing target model on [source]...
Test, loss: 9.628, prec: 15.9%, Time: 2.390
Testing target model on [target]...
Test, loss: 10.641, prec: 10.3%, Time: 1.202
 87%|███████████████████████████████████████████████████████████████████████████████████████████████████▋               | 26/30 [07:17<01:06, 16.73s/it]Training target model...
Train Epoch: 27, Batch:937, S: [c: 0.000, d: 1.447], Time: 12.648
Testing target model on [source]...
Test, loss: 8.766, prec: 11.1%, Time: 3.055
Testing target model on [target]...
Test, loss: 8.690, prec: 10.1%, Time: 1.376

..   bad effect,  any problems?

**Comment by hou-yz** [comment]
Hi,

Thank you for your interest. However, we have no official support for digits datasets using ADDA. The current [discriminator architecture](https://github.com/hou-yz/DA_visualization/blob/main/SFIT/models/classifier_shot.py#L143) in ADDA is designed for stronger classifiers like ResNet50 in VisDA datasets. Directly applying such a strong discriminator might introduce difficulties to the [3-layerl-convolution-classifier](https://github.com/hou-yz/DA_visualization/blob/main/SFIT/models/classifier_shot.py#L113) in digits datasets in terms of adversarial training. 

Feel free to adjust the discriminator architecture a little bit (probably remove a few layers or see other ADDA implementations) to facilitate the digits datasets.

Yunzhong
